// <auto-generated />
using System;
using Banco.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Banco.Migrations
{
    [DbContext(typeof(MyDataContext))]
    partial class MyDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Banco.Models.AberturaConta", b =>
                {
                    b.Property<int>("idCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idCliente");

                    b.Property<DateTime>("dataAberturaContaCliente")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("nomeCliente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("numeroBilheteIdentidadeCliente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("numeroContaCliente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("numeroIbanCliente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("saldoContaCliente")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("tipoMoedaCliente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("idCliente");

                    b.ToTable("aberturaconta");
                });
#pragma warning restore 612, 618
        }
    }
}
