// <auto-generated />
using Frutticultura.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Frutticultura.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20241024210223_GerandoTabelaArvore")]
    partial class GerandoTabelaArvore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Frutticultura.Models.Arvore", b =>
                {
                    b.Property<int>("idArvore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("descricaoArvore")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nomeArvore")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("idArvore");

                    b.ToTable("arvore");
                });

            modelBuilder.Entity("Frutticultura.Models.Frutta", b =>
                {
                    b.Property<int>("idFrutta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("descricaoFrutta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nomeFrutta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("idFrutta");

                    b.ToTable("fruta");
                });
#pragma warning restore 612, 618
        }
    }
}
