// <auto-generated />
using System;
using Farmacia.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Farmacia.Migrations
{
    [DbContext(typeof(MyDataContext))]
    [Migration("20241103112638_GerandoMinhaBase")]
    partial class GerandoMinhaBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Farmacia.Models.Comprimido", b =>
                {
                    b.Property<int>("idComprimido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idComprimido");

                    b.Property<DateTime>("dataExpiracaoComprimido")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("dataFabricoComprimido")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("nomeComprimido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("precoComprimido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("stockComprimido")
                        .HasColumnType("int");

                    b.HasKey("idComprimido");

                    b.ToTable("comprimido");
                });
#pragma warning restore 612, 618
        }
    }
}
