// <auto-generated />
using System;
using Farmacia.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Farmacia.Migrations
{
    [DbContext(typeof(MyDataContext))]
    partial class MyDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Farmacia.Models.Ampola", b =>
                {
                    b.Property<int>("idAmpola")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idAmpola");

                    b.Property<DateTime>("dataExpiracaoAmpola")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("dataFabricoAmpola")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("descricaoAmpola")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nomeAmpola")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("precoAmpola")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("stockAmpola")
                        .HasColumnType("int");

                    b.HasKey("idAmpola");

                    b.ToTable("Ampolas");
                });

            modelBuilder.Entity("Farmacia.Models.Comprimido", b =>
                {
                    b.Property<int>("idComprimido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idComprimido");

                    b.Property<DateTime>("dataExpiracaoComprimido")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("dataFabricoComprimido")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("descricaoComprimido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nomeComprimido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("precoComprimido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("stockComprimido")
                        .HasColumnType("int");

                    b.HasKey("idComprimido");

                    b.ToTable("comprimido");
                });

            modelBuilder.Entity("Farmacia.Models.Soro", b =>
                {
                    b.Property<int>("idSoro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idSoro");

                    b.Property<DateTime>("dataExpiracaoSoro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("dataFabricoSoro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("descricaoSoro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nomeSoro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("precoSoro")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("stockSoro")
                        .HasColumnType("int");

                    b.HasKey("idSoro");

                    b.ToTable("Soros");
                });

            modelBuilder.Entity("Farmacia.Models.Vitamina", b =>
                {
                    b.Property<int>("idVitamina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idVitamina");

                    b.Property<DateTime>("dataExpiracaoVitamina")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("dataFabricoVitamina")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("descricaoVitamina")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nomeVitamina")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("precoVitamina")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("stockVitamina")
                        .HasColumnType("int");

                    b.HasKey("idVitamina");

                    b.ToTable("Vitaminas");
                });

            modelBuilder.Entity("Farmacia.Models.Xarope", b =>
                {
                    b.Property<int>("idXarope")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idXarope");

                    b.Property<DateTime>("dataExpiracaoXarope")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("dataFabricoXarope")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("descricaoXarope")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nomeXarope")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("precoXarope")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("stockXarope")
                        .HasColumnType("int");

                    b.HasKey("idXarope");

                    b.ToTable("Xaropes");
                });
#pragma warning restore 612, 618
        }
    }
}
